services:
  db-taller:
    image: postgres:15-alpine
    container_name: taller_mecanico_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taller
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-taller:
    build:
      context: ./taller-mecanico-back
      dockerfile: Dockerfile
    container_name: taller_mecanico_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-taller:5432/taller
    ports:
      - "8080:8080"
    depends_on:
      - db-taller

  frontend-taller:
    build:
      context: ./taller-mecanico-front
      dockerfile: Dockerfile
    container_name: taller_mecanico_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend-taller

volumes:
  postgres_data:
